[general]
working_directory = "~"

[bell]
command = "None"

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
opacity = 0.85

[window.padding]
x = 10
y = 10
